var tableauQuestion = [
    {   question : "Aşağıdakilerden hangisi, soğutma sisteminde yapılması gereken kontrollerden birisidir?",
        propositionA : "Elektrolit kaçağı",
        propositionB : "Yağ kaçağı",
        propositionC : "Hidrolik yağ kaçağı",
        propositionD : "Su kaçağı",
        reponse : "D"},
		
    {   question : "Aşağıdakilerden hangisi, aracın geri manevrası esnasında arkada bulunan diğer araçların durumdan haberdar edilmesi amacıyla yanar?",
        propositionA : "Sinyal lambaları",
        propositionB : "Geri vites lambaları",
        propositionC : "Sis lambaları",
        propositionD : "Park lambaları",
        reponse : "B"},
		
    {   question : "Ticari amaçla yük taşımacılığı yapan ve azami ağırlığı 3,5 tonu geçen araçların şoförlerinin, 24 saatlik herhangi bir süre içinde toplam olarak kaç saatten fazla araç sürmeleri yasaktır??",
        propositionA : "9",
        propositionB : "7",
        propositionC : "6",
        propositionD : "8",
        reponse : "A"},
	
	{   question : "Aracın gösterge panelinde bulunan devir saati sürücüye aşağıdakilerden hangisini bildirir?",
        propositionA : "Km/saat cinsinden aracın hızını",
        propositionB : "Aracın katettiği toplam kilometreyi",
        propositionC : "Dev/dak cinsinden motorun devrini ",
        propositionD : "Uzun hüzme anahtarının açık olduğunu",
        reponse : "C"},
		
	{   question : "Aşağıdakilerden hangisi, yaralının taşınması sırasında ilk yardımcının uyması gereken kurallardandır?",
        propositionA : "Kendi kapasitesinden fazla ağırlık taşımalıdır.",
        propositionB : "Ani dönme ve bükülme gibi hareketler yapmalıdır.",
        propositionC : "Yangın, göçük ve patlama tehlikesinin devam ettiği durumları önemsememelidir",
        propositionD : "Kendinin ve yaralının güvenliğinden emin olmalıdır. ",
        reponse : "D"},
		
	{   question : "Motosikletlerde ilk 3 yaş sonunda kaç yılda bir muayene yaptırılması zorunludur?",
        propositionA : "2",
        propositionB : "3",
        propositionC : "4",
        propositionD : "1",
        reponse : "A"},
	
	{   question : "Trafikte kırmızı ışıkta beklerken ışık sarıya döner dönmez önündeki araca korna çalan, ışığın yeşile dönmesi için 1 saniye bile bekleyemeyen sürücünün bu davranışı için aşağıdakilerden hangisi söylenebilir?",
        propositionA : "Saygılı",
        propositionB : "Telaşsız",
        propositionC : "Orospu Çocuğu,Annesiz,Karaktersiz,Dolandırıcı,İt Dölü,Babası Gulliatone",
        propositionD : "Efendi",
        reponse : "C"},
		
	{   question : "Yaz aylarında kış lastiklerinin kullanılması aşağıdakilerden hangisine neden olur?",
        propositionA : "Aracın maksimum hızının artmasına",
        propositionB : "Yakıt tüketiminin azalmasına",
        propositionC : "Fren sisteminin bozulmasına",
        propositionD : "Lastiklerin daha çabuk aşınmasına",
        reponse : "D"},
		
	{   question : "Motor hareketinin vites kutusuna iletilmesini sağlayan sistem aşağıdakilerden hangisidir?",
        propositionA : "Marş",
        propositionB : "Ateşleme",
        propositionC : "Gaz",
        propositionD : "Debriyaj",
        reponse : "A"},
		
	{   question : "Seyahate başlamadan önce koltuk ve ayna ayarlarının yapılmasının sebebi aşağıdakilerden hangisidir?",
        propositionA : "Yakıt tüketimini azaltmak",
        propositionB : "Sürüş konforu ve güvenliğini sağlamak",
        propositionC : "Aracın ivmelenme süresini artırmak",
        propositionD : "Karıya kıza rahat bakmak",
        reponse : "B"},
]
