Lang = {
  -- Menu Text:
  ['button_yes']         	    = 'Evet',
  ['button_no']         	    = 'Hayır',
  ['button_return']         	= 'Dönüs',
  ['rename_mech_shop']        = 'Mekanik Adını Yeniden Adlandır',
  ['sell_mech_shop']          = 'Mekanigi Sat',
  ['employees_action']        = 'Mekanik İsçileri',
  ['hire_employee']           = 'Çalısan İste',
  ['employee_list']           = 'İsçi listesi',
  ['fire_employee']           = 'Yangın Çalısanı',
  ['employee_job_grade']      = 'İs Derecesi Yönetme',
  ['accounts_action']         = 'Hesaplar',
  ['account_withdraw']        = 'Para Çek',
  ['account_deposit']         = 'Para Depola',
  ['storage_withdraw']        = 'Ögeleri Çek',
  ['storage_deposit']         = 'Ögeleri Depola',
  ['craft_item']              = 'Parça İmalat',
  ['view_recipe']             = 'Tarifi Görüntüle',

  -- GENERAL | NOTIFICATIONS
  ['not_enough_money']        = 'Yeterli paran yok.',
  ['mech_shop_bought']        = 'Bir ~b~mekanik~s~ satın aldınız ve ~g~$%s~s~ ödediniz',
  ['mech_shop_sold']          = '~b~Mekanigini~s~ sattın ve ~g~$%s~s~ elde ettin',
  ['not_your_mech_shop']      = 'Bu mekanik dükkanın sahibi degilsin',
  ['mech_shop_renamed']       = 'Mekanik magazanızın adını su sekilde degistirin: ~b~%s~s~',
  ['no_access']               = 'Erisim Yok',
  ['invalid_amount']          = 'Geçersiz Tutar',
  ['repair_kit_broke']        = 'Tamir Kiti imha edildi.',
  ['repairkit_veh_repaired']  = 'Araç motoru tamir edildi, en yakın mekanige gidin.',
  ['no_vehicle_nearby']       = 'Yakında araç yok.',
  ['no_players_nearby']       = 'Yakında araç yok.',

  -- EMPLOYEE | NOTIFICATIONS
  ['no_employees_hired']      = 'Mekaniginizde çalısan yok',
  ['mech_employee_fired']     = 'Makine dükkanından kovuldun.',
  ['target_alrdy_has_job_g']  = '%s zaten o is notuna sahip.',
  ['your_job_grade_updated']  = 'İs notunuz su sekilde güncellendi: %s.',
  ['you_updat_job_grade_for'] = 'İs notun u%s olarak güncellediniz: %s.',
  ['mix_max_job_grade']       = 'Min İs Notu: 0 | Maksimum İs Notu:% s.',
  ['already_hired']           = 'Oyuncu zaten ise alındı.',
  ['you_recruited_x']         = 'İse alındınız: %s.',
  ['you_have_been_recruited'] = 'Mekanige ise alındınız',

  -- ACCOUNTS & STORAGE & WORKBENCH | NOTIFICATIONS
  ['you_withdrew_x_amount']   = 'Para çektiniz ~g~$%s~s~.',
  ['withdrawal_denied']       = 'Para çekme reddedildi, hesap bakiyesi yetersiz.',
  ['you_deposited_x_amount']  = 'Depoladınız ~g~$%s~s~.',
  ['storage_inv_empty']       = 'Depolama Envanteri Bos.',
  ['storage_deposited_x']     = 'Depoya %sx %s depoladınız',
  ['not_enough_items']        = 'Para yatırmak için yeterli öge yok.',
  ['storage_withdrew_x']      = 'Depolama alanından %sx %s çektiniz',
  ['too_high_count']          = 'Depolama envanterine kıyasla istenen miktar çok yüksek',
  ['not_enough_materials']    = 'Biraz daha malzemeye ihtiyacın var, tarifi kontrol et!',
  ['crafting_in_progress']    = 'Zaten isleniyor, lütfen bekleyin!',

  -- VEHICLE BODY REPAIRS | NOTIFICATIONS
  ['car_jack_carry']          = 'Üzerinde bir kriko tasımalısın.',
  ['raise_and_analyze']       = 'Parçaları takmadan önce aracı bir kriko üzerinde kaldırın ve aracı analiz edin.',
  ['analyze_veh_first']       = 'Parçaları takmadan önce aracı analiz edin.',
  ['all_doors_intact']        = 'Tüm kapılar onarılmıs ve saglam.',
  ['trunk_already_installed'] = 'Gövde zaten kurulu.',
  ['hood_already_installed']  = 'Hood zaten kurulu.',
  ['all_wheels_intact']       = 'Tüm tekerlekler tamir edilmis ve saglam.',
  ['all_body_repairs_done']   = 'Tüm vücut onarımları yapılır. Aracı indirin!',
  ['finish_current_install']  = 'Mevcut kurulumunuzu tamamlayın',
  ['veh_already_analyzed']    = 'Araç zaten analiz edildi, isinizi yapın!',
  ['raise_veh_b4_analyze']    = 'Aracı analiz etmeden önce aracı bir kriko üzerinde kaldırın.',

  -- LIFT REPAIRS & HEALTH PARTS | NOTIFICATIONS
  ['lift_cannot_go_higher']   = 'Lift daha yüksege çıkamaz!',
  ['lift_cannot_go_lower']    = 'Kaldırma asagı inemez!',
  ['veh_must_be_on_lift']     = 'Araç bir asansöre baglanmalıdır.',
  ['veh_must_be_inspected']   = 'Saglık parçalarını onarmadan önce aracı inceleyin.',
  ['health_part_exceeded']    = 'Saglık Bölümü Degeri 10.0 ı geçemez',
  ['not_decrease_health_val'] = 'Mevcut Saglık Bölümü Degerini düsüremezsiniz.',
  ['not_decrse_or_same_val']  = 'Aynı saglık degerini düsüremez veya ayarlayamazsınız, daha yüksek bir deger olmalıdır!',
  ['need_more_materials']     = 'Seçilen degere ulasmak için daha fazla malzemeye ihtiyacınız var.',
  ['you_rep_health_part']     = 'Onardınız: %s. Yeni deger: %s',

  -- NPC JOB | NOTIFICATIONS
  ['npc_shout_msg']           = 'Hey! Arabamı tamir edebilir misin lütfen?',
  ['npc_need_repair_kit']     = 'Bir tamir setine ihtiyacınız var.',
  ['npc_kit_broke']           = 'Onarım sırasında kitiniz kırıldı',
  ['npc_veh_repaired']        = 'Araç tamir edildi. NPC den nakit toplayın.',
  ['npc_thanking_msg']        = 'Çok tesekkür ederim adios!',
  ['npc_cancel_job_death']    = 'Öldün! İs iptal edildi.',
  ['npc_job_cancel_by_ply']   = 'Devam eden mevcut isinizi iptal ettiniz..',
  ['npc_job_cash_reward']     = 'NPC den ~g~$%s~s~ kazandınız.',

  -- Draw 3D texts:
  ['mech_shop_manage']        = '~r~[E]~s~ Yönet',
  ['no_access_to_shop']       = 'Erisim reddedildi',
  ['press_to_buy_shop']       = '~r~[E]~s~ Mekanik Satın Al',
  ['only_one_mech_shop']      = 'Sadece bir mekanigin olabilir',
  ['repair_here']             = '~g~[E]~s~ ONARIM ARACI',
  ['press_to_storage']        = '~r~[E]~s~ Depolama',
  ['press_to_workbench']      = '~r~[E]~s~Tezgah',
  ['lower_jack']              = 'Asagı İndir',
  ['raise_jack']              = 'Yukarı Kaldır',
  ['analyze_here']            = '~r~[E]~s~ Burada Analiz Et',
  ['install_body_part']       = '~r~[G]~s~ Gövde Parçasını Takın',
  ['park_on_lift']            = '~r~[E]~s~ Lift Üzerinde Parket',
  ['lift_occupied']           = 'Lift Dolu',
  ['remove_or_move_veh']      = '~r~[G]~s~ Aracı Kaldır | ~y~[Arrow Up/Down]~s~ Aracı Hareket Ettir',
  ['no_veh_to_control']       = 'Kontrol Edilecek Araç Yok',
  ['health_rep_here']         = '~r~[E]~s~ Burada Onarın',
  ['inspect_here']            = '~r~[E]~s~ Burada İncele',
  ['repair_engine']           = '~r~[E]~s~ Onarım Motoru',
  ['npc_repair_veh']          = '~r~[E]~s~ Onarım Aracı',
  ['npc_collect_cash']        = '~r~[E]~s~ Nakit Topla',
  
  -- Progress Bar Texts:
  ['repairing_veh_kit']       = 'ARAC ONARILIYOR',
  ['crafting_item']           = 'ÜRETİLİYOR %s',
  ['progbar_lowering_jack']   = 'ARAÇ İNDİRİLİYOR',
  ['progbar_raising_jack']    = 'ARAÇ KALDIRILIYOR',
  ['progbar_inspecting_veh']  = 'ARAÇ MUAYENE EDİLİYOR',
  ['progbar_analyzing_veh']   = 'ARAÇ ANALİZ EDİLİYOR',
  ['lift_repairing_veh']      = 'ONARILIYOR: %s',
  ['progbar_npc_fix']         = 'NPC ARACI ONARILIYOR',
  ['progbar_npc_cash']        = 'PARA TOPLANIYOR',

  -- Blip Texts:
  ['vacant_shops']            = 'Bos Mekanik Dükkanı',
  ['npc_repair_job']          = 'Onarım NPC Aracı',
}
